package com.example.ui.navigation

sealed class Screen(val route: String) {
    data object Home : Screen("home")
    data object Chat : Screen("chat")
    data object Voice : Screen("voice")
    data object Tasks : Screen("tasks")
    data object Alerts : Screen("alerts")
    data object Prayer : Screen("prayer")
    data object Games : Screen("games")
    data object Settings : Screen("settings")
    data object MediaGallery : Screen("media_gallery")
    data object VideoPlayer : Screen("video_player")
    data object AudioPlayer : Screen("audio_player")
    data object Notes : Screen("notes")
    data object BarcodeScanner : Screen("barcode_scanner")
    data object PdfReader : Screen("pdf_reader")
    data object Downloads : Screen("downloads")
    data object SystemDashboard : Screen("system_dashboard")
    data object Weather : Screen("weather")
    data object Calculator : Screen("calculator")
    data object Converter : Screen("converter")
    data object IslamicHub : Screen("islamic_hub")
    data object Tasbih : Screen("tasbih")
    data object Clients : Screen("clients_manager")
    data object Invoices : Screen("invoices_manager")
    data object Projects : Screen("projects_manager")
    data object ProjectDetail : Screen("project_detail/{projectId}") {
        fun createRoute(projectId: String) = "project_detail/$projectId"
    }
    data object WebsiteManager : Screen("website_manager")
    data object UnifiedAlerts : Screen("unified_alerts")
    data object AIFileAssistant : Screen("ai_file_assistant")
    data object VoiceNotes : Screen("voice_notes")
    data object AIImageTools : Screen("ai_image_tools")
    data object GlobalSearch : Screen("global_search")
    data object Tools : Screen("tools")
    data object VideoCompressor : Screen("video_compressor")
    data object VideoTrimmer : Screen("video_trimmer")
    data object VideoToAudio : Screen("video_to_audio")
    data object ImageCompressor : Screen("image_compressor")
    data object ImageTextEditor : Screen("image_text_editor")
    data object PhotoResizerCropper : Screen("photo_resizer_cropper")
    data object ImageToTextOcr : Screen("image_to_text_ocr")
    data object ClipboardHistory : Screen("clipboard_history")
    data object Teleprompter : Screen("teleprompter")
    data object SecureNotes : Screen("secure_notes")
    data object DailyChecklist : Screen("daily_checklist")
    data object HabitCounter : Screen("habit_counter")
    data object PomodoroTimer : Screen("pomodoro_timer")
    data object AudioCutter : Screen("audio_cutter")
    data object SocialMediaSizeMaker : Screen("social_media_size_maker")
    data object WatermarkTool : Screen("watermark_tool")
    data object CollageMaker : Screen("collage_maker")
    data object PostQuoteMaker : Screen("post_quote_maker")
    data object TextToSpeech : Screen("text_to_speech")
    data object ImageStudio : Screen("image_studio")
    data object VideoStudio : Screen("video_studio")
    data object AudioStudio : Screen("audio_studio")
    data object PdfStudio : Screen("pdf_studio")
    data object DevTextToolkit : Screen("text_dev_toolkit")
    data object SmartCalculator : Screen("smart_calculator")
    data object QrShareHub : Screen("qr_share_hub")
    data object QrWaDirect : Screen("qr_wa_direct")
    data object QrGenerator : Screen("qr_generator")
    data object QrQuickShare : Screen("qr_quick_share")
    data object QrPrivateShare : Screen("qr_private_share")
    data object QrLinkCleaner : Screen("qr_link_cleaner")
    data object TimerClockHub : Screen("timer_clock")
    data object DevStopwatch : Screen("dev_stopwatch")
    data object DevCountdown : Screen("dev_countdown")
    data object DevInterval : Screen("dev_interval")
    data object SecurityPrivacyHub : Screen("security_privacy")
    data object SecPassGen : Screen("sec_pass_gen")
    data object SecPassCheck : Screen("sec_pass_check")
    data object SecPhotoMetadata : Screen("sec_photo_metadata")
    data object DevDecisionHub : Screen("random_decision")
    data object DevRandomPicker : Screen("dev_random_picker")
    data object DevDecisionWheel : Screen("dev_decision_wheel")
    data object ToolCategoryDetail : Screen("tools_category/{categoryId}") {
        fun createRoute(categoryId: String) = "tools_category/$categoryId"
    }
}
